iname: CI
on: [push, pull_request]

env:
  BIN_NAME: commandant-rs
  ARTIFACTS_DIR: artifacts
  RUST_PROJECT: github.com/kennethdsheridan/commandant-rs

jobs:
  build:
    runs-on: self-hosted  # Changed to self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo "Preparing to build for Linux..."
          cargo build --release --target x86_64-unknown-linux-gnu
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-binary
          path: target/x86_64-unknown-linux-gnu/release/${{ env.BIN_NAME }}

  test:
    needs: build
    runs-on: self-hosted  # Changed to self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: cargo test --verbose

  document:
    needs: test
    runs-on: self-hosted  # Changed to self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Documentation
        run: cargo doc --no-deps
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: target/doc
