# config.yaml

# General Configuration
general:
  log_directory: "logs"
  log_level: "Info"
  database_path: "commandant-rs_database_file.db"

# Web Server Configuration
web_server:
  port: 8080
  host: "127.0.0.1"

# Stress Test Configuration
stress_test:
  cpu:
    cores: 8
    timeout: "30s"
  options:
    - "--metrics-brief"
    - "--verbose"

# AI Model Configuration
ai_model:
  pretrained_model_path: "/path/to/pretrained/model"

# Overwatch Configuration
overwatch:
  output_file: "cpu_stats.txt"
  interval: 5  # in seconds

# Database Operations
database_ops:
  enabled: true
